// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";

import * as AuthEmailVerifiedRoute from "@/app/(auth)/email-verified/page.info";
import * as AuthForgotPasswordRoute from "@/app/(auth)/forgot-password/page.info";
import * as AuthResetPasswordRoute from "@/app/(auth)/reset-password/page.info";
import * as AuthSignInRoute from "@/app/(auth)/sign-in/page.info";
import * as AuthSignUpRoute from "@/app/(auth)/sign-up/page.info";
import * as DashboardAdminRoute from "@/app/(dashboard)/admin/page.info";
import * as DashboardUserAssetsRoute from "@/app/(dashboard)/user/assets/page.info";
import * as DashboardUserDashboardRoute from "@/app/(dashboard)/user/dashboard/page.info";
import * as DashboardUserInvestmentsRoute from "@/app/(dashboard)/user/investments/page.info";
import * as DashboardUserRoute from "@/app/(dashboard)/user/page.info";
import * as DashboardUserReportsRoute from "@/app/(dashboard)/user/reports/page.info";
import * as tempKeyRoute from "@/app/(dashboard)/user/transactions/page.info";
import * as ApiAssetsRoute from "@/app/api/assets/route.info";
import * as ApiAuthAllRoute from "@/app/api/auth/[...all]/route.info";
import * as ApiBudgetsRoute from "@/app/api/budgets/route.info";
import * as ApiInvestmentsRoute from "@/app/api/investments/route.info";
import * as ApiTransactionsRoute from "@/app/api/transactions/route.info";
import * as HomeRoute from "@/app/page.info";

import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({}),
};

export const Home = makeRoute("/", {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const AuthEmailVerified = makeRoute("/(auth)/email-verified", {
  ...defaultInfo,
  ...AuthEmailVerifiedRoute.Route,
});
export const AuthForgotPassword = makeRoute("/(auth)/forgot-password", {
  ...defaultInfo,
  ...AuthForgotPasswordRoute.Route,
});
export const AuthResetPassword = makeRoute("/(auth)/reset-password", {
  ...defaultInfo,
  ...AuthResetPasswordRoute.Route,
});
export const AuthSignIn = makeRoute("/(auth)/sign-in", {
  ...defaultInfo,
  ...AuthSignInRoute.Route,
});
export const AuthSignUp = makeRoute("/(auth)/sign-up", {
  ...defaultInfo,
  ...AuthSignUpRoute.Route,
});
export const DashboardAdmin = makeRoute("/(dashboard)/admin", {
  ...defaultInfo,
  ...DashboardAdminRoute.Route,
});
export const DashboardUser = makeRoute("/(dashboard)/user", {
  ...defaultInfo,
  ...DashboardUserRoute.Route,
});
export const DashboardUserAssets = makeRoute("/(dashboard)/user/assets", {
  ...defaultInfo,
  ...DashboardUserAssetsRoute.Route,
});
export const DashboardUserDashboard = makeRoute("/(dashboard)/user/dashboard", {
  ...defaultInfo,
  ...DashboardUserDashboardRoute.Route,
});
export const DashboardUserInvestments = makeRoute(
  "/(dashboard)/user/investments",
  {
    ...defaultInfo,
    ...DashboardUserInvestmentsRoute.Route,
  },
);
export const DashboardUserReports = makeRoute("/(dashboard)/user/reports", {
  ...defaultInfo,
  ...DashboardUserReportsRoute.Route,
});
export const tempKey = makeRoute("/(dashboard)/user/transactions", {
  ...defaultInfo,
  ...tempKeyRoute.Route,
});
export const ApiAssets = makeRoute("/api/assets", {
  ...defaultInfo,
  ...ApiAssetsRoute.Route,
});
export const ApiAuthAll = makeRoute("/api/auth/[...all]", {
  ...defaultInfo,
  ...ApiAuthAllRoute.Route,
});
export const ApiBudgets = makeRoute("/api/budgets", {
  ...defaultInfo,
  ...ApiBudgetsRoute.Route,
});
export const ApiInvestments = makeRoute("/api/investments", {
  ...defaultInfo,
  ...ApiInvestmentsRoute.Route,
});
export const ApiTransactions = makeRoute("/api/transactions", {
  ...defaultInfo,
  ...ApiTransactionsRoute.Route,
});
